### PR TITLE
Handle Fink livestreams

### PR DESCRIPTION
**Pull request by JulienPeloton**
This PR adds new classes to manipulate Fink livestreams (in addition to data coming from the  REST API):
- [ ] add a Query form (`FinkDESCQueryForm`)
- [ ] add a class to handle livestream (`FinkDESC`)
- [ ] add a method to fetch alerts using the fink-client consumer `FinkDESC.fetch_alerts`
- [ ] add a method to translate data for TOM `FinkDESC.to_generic_alert`
- [ ] update the test suite
- [ ] TBC...

### CODE REVIEW

**Comment by dmcollom** [comment]
Hi @JulienPeloton -- my apologies for the delay. I actually left LCO in September, but I'm trying to stay involved with the project as best I can in my spare time.

Things look good, but it looks like there are some syntax errors in the widget definitions for the new form that need to be cleaned up.  I would do it, but I'm not entirely sure what's intended in terms of label vs. display name vs. something else.

The other thing I would note is that the README should be updated with some information about the additional broker option, as well as how to install it into `settings.py`.

**Comment by JulienPeloton** [comment]
Hi @dmcollom -- thanks for following up. Actually, I still have code to push before review. I'll let you know when code is ready (no rush though!)

**Comment by jchate6** [comment]
@JulienPeloton any updates on the status of this?

**Comment by JulienPeloton** [comment]
superseded by #51

**Pull request closed without merging**
